/** @file test_vulkan_stubs.cc
 *  Unit tests for Vulkan compute shader C++ stub code generation.
 *
 *  Each test includes a generated stub header and calls the dispatch function
 *  with mock data to verify:
 *   - The generated stub compiles (header-only)
 *   - The dispatch function accepts the correct parameter types
 *   - vkCmdDispatch is invoked with proper workgroup division
 */

#include <gtest/gtest.h>

// Mock Vulkan types and helpers
#include "mocked_vulkan.hpp"

// Forward declarations for generated kernels — these mirror what the stub generator produces.
// In CI the real generated headers go into build/generated/vulkanized/kernels/ and are included.

// ---- Multi-arg kernel (2D) struct layout from vulkan_cpp_stub_visitor ----

struct FRM_float_multi_arg {
    float*         data  = nullptr;
    uint32_t   rows  = 0;
    uint32_t   cols  = 0;
};

// Forward-declare the dispatch function (generated by vulkan_cpp_stub_visitor)
// inline void vecmath_dispatch(...);  // Will be provided by actual stub header

