


program: header parfor_space parfor_parameters body


parfor_parameters: "PARAMETERS" declaration ("," declaration)*

header: "PROGRAM" "(" string ")" workgroup_properties*

workgroup_properties: "workgroup" "{" "x" ":" expression "," "y" ":" expression "," "z" ":" expression "}"
| "shared" declaration ";"

parfor_space: "OFFLOAD_PARFOR_1D_PARAM" "(" IDENT "," expression "," parfor_parameters_list ")" 
| "OFFLOAD_PARFOR_2D_PARAM" "(" IDENT "," IDENT "," expression "," parfor_parameters_list ")" 
| "OFFLOAD_PARFOR_3D_TRIANGULAR_PARAM" "(" IDENT "," IDENT "," expression "," parfor_parameters_list ")" 

parfor_parameters_list: "(" parameter ("," parameter)* ")"
parameter: IDENT

body: "BEGIN" statement+ "END_PROGRAM"

statement: for_statement
| if_statement
| declaration ";"
| assignment ";"
| "OVERFLOW_CHECK_ADD" "(" lhs "," expression ")" ";"


for_statement: "for" "(" for_loop_var ";" condition ";" increment ")" statement

if_statement: "if" "(" condition ")" block

for_loop_var: type IDENT "=" expression 

// in the AST becomes <expr> <op> <expr>
condition: IDENT compare_operator expression

compare_operator: LT | GT | LTE | GTE | EQ | NEQ
LT: "<"
GT: ">"
LTE: "<="
GTE: ">="
EQ: "=="
NEQ: "!="

increment: IDENT INC_OP -> inc_postfix | INC_OP IDENT -> inc_prefix
INC_OP: "++" | "--"

declaration: "const" type IDENT ("=" expression)? -> const_decl
| type IDENT  ("=" expression)? -> decl

type: "int" -> int
| "size_t" -> int
| "float" -> float
| "rlmm_float" -> float
| "rlmm_float_small" -> float
| "fixed_size_vector" "<" type "," expression ">"  "&"
| "flexible_rows_matrix" "<" type "," expression "," expression ">"  "&"
| "fixed_size_matrix" "<" type "," expression "," expression ">"  "&"


block: "{" statement* "}"

assignment: lhs assign_operator expression

ASSIGN_OP: "=" | "+=" | "-=" | "*=" | "/="
assign_operator: ASSIGN_OP

lhs: IDENT ( "[" expression ("," expression)*  "]" )?

expression: base_expr (arith_operator expression)?

ARITH_OP: "*" | "/" | "+" | "-"
arith_operator: ARITH_OP

base_expr: limit_expr | number_term | lhs | type "(" expression ")" | "!" expression


limit_expr: "limit" "<" expression ">" "(" expression ")"
number_term: NUMBER -> number

// Define the Comment Terminals
COMMENT: "//" /[^\n]/* | "/*" /.*?/ "*/"

// Instruct the lexer to skip them
%ignore COMMENT
%ignore /\s+/ // Ignores whitespace


string : ESCAPED_STRING

NUMBER: /([0-9]+\.[0-9]*|\.[0-9]+|[0-9]+)[fF]?/


%import common.ESCAPED_STRING
%import common.CNAME -> IDENT
%import common.WS_INLINE
%import common.WS
%ignore WS_INLINE
