#include A
#ifndef  B
#define GUARANTEED_TO_LEARN_CPP
#include C
#include A
#ifndef  B
#define GUARANTEED_TO_LEARN_CPP
#include C
#include A
#ifndef  B
#define GUARANTEED_TO_LEARN_CPP
#include C
#include A
#ifndef  B
#define GUARANTEED_TO_LEARN_CPP
#include C
#include A
#ifndef  B
#define GUARANTEED_TO_LEARN_CPP
#include C
#include A
#ifndef  B
#define GUARANTEED_TO_LEARN_CPP
#include C
#include A
#ifndef  B
#define GUARANTEED_TO_LEARN_CPP
#include C
#include A
#ifndef  B
#define GUARANTEED_TO_LEARN_CPP
#include C
#include A
#ifndef  B
#define GUARANTEED_TO_LEARN_CPP
#include C
#include A
#ifndef  B
#define GUARANTEED_TO_LEARN_CPP
#include C
#include A
#ifndef  B
#define GUARANTEED_TO_LEARN_CPP
#include C
#include A
#ifndef  B
#define GUARANTEED_TO_LEARN_CPP
#include C
#include A
#ifndef  B
#define GUARANTEED_TO_LEARN_CPP
#include C
